name: Install Report
description: Report an install issue in Hell Jump
labels: ["install issue"]
body:

  - type: textarea
    id: description
    attributes:
      label: Install issue descriptiom
      placeholder: Describe the issue here...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Go to...\n2. Jump on...\n3. See error"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - Linux

  - type: dropdown
    id: store
    attributes:
      label: Store
      options:
        - Itch.io
        - Game Jolt
        - Snap Store
